name: Detect Microservice Test Tags

description: Detects which tags should be run based on changed paths

inputs:
  before:
    description: Git SHA before the change
    required: true
  after:
    description: Git SHA after the change
    required: true
  service_tag_map:
    description: Newline-delimited path -> tag mappings
    required: true

outputs:
  tags:
    description: Comma-separated tags to include

runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        BEFORE="${{ inputs.before }}"
        AFTER="${{ inputs.after }}"

        if [ -z "$BEFORE" ]; then
          echo "🔍 'before' SHA is empty. Using HEAD^ as fallback."
          BEFORE=$(git rev-parse "${AFTER}^")
          echo "✅ Fallback BEFORE=$BEFORE"
        fi

        echo "🔧 Using BEFORE=$BEFORE"
        echo "🔧 Using AFTER=$AFTER"

        CHANGED=$(git diff --name-only "$BEFORE" "$AFTER")
        echo "🔄 Changed files:"
        echo "$CHANGED"

        TAGS=""
        while read -r line; do
          path=$(echo "$line" | cut -d'>' -f1 | xargs)
          tag=$(echo "$line" | cut -d'>' -f2 | xargs)
          echo "🔍 Matching path: $path against changed files:"
          echo "$CHANGED" | while read changed; do
            echo "   🔸 Changed: $changed"
            if echo "$CHANGED" | grep -q "^$path"; then
              echo "   ✅ Match found! Adding tag: $tag"
              TAGS="$TAGS,$tag"
            else
              echo "   ❌ No match for this file"
            fi
          done
        done <<< "${{ inputs.service_tag_map }}"

        TAGS=$(echo "$TAGS" | sed 's/^,//')
        echo "✅ Detected tags: $TAGS"
        echo "tags=$TAGS" >> $GITHUB_OUTPUT
