name: Detect Microservice Test Tags

description: Detects which tags should be run based on changed paths

inputs:
  before:
    description: Git SHA before the change
    required: true
  after:
    description: Git SHA after the change
    required: true
  service_tag:
    description: Tag to emit when a change is detected
    required: true

outputs:
  tags:
    description: Comma-separated tags to include
    value: ${{ steps.set.outputs.tags }}

runs:
  using: "composite"
  steps:
    - id: set
      shell: bash
      run: |
        set -euo pipefail

        BEFORE="${{ inputs.before }}"
        AFTER="${{ inputs.after }}"

        # Fallback when 'before' is empty (common with workflow_run)
        if [ -z "$BEFORE" ]; then
          echo "ℹ️ 'before' SHA empty; using parent of AFTER"
          BEFORE=$(git rev-parse "${AFTER}^")
        fi

        echo "Diff range: $BEFORE..$AFTER"

        CHANGED=$(git diff --name-only --diff-filter=ACMRD "$BEFORE" "$AFTER" -- || true)
        echo "Changed files:"
        echo "$CHANGED"

        TAGS=""
        if echo "$CHANGED" | grep -qE '^src/'; then
          TAGS="${{ inputs.service_tag }}"
        fi
        
        echo "✅ Detected tags: $TAGS"
        echo "tags=$TAGS" >> $GITHUB_OUTPUT