name: Detect Microservice Codebase Changes

description: Emits a test tag when codebase changes are detected

inputs:
  before:
    description: Git SHA before the change
    required: true
  after:
    description: Git SHA after the change
    required: true
  service_tag:
    description: Tag to emit when a change is detected
    required: true

outputs:
  tag:
    description: Tag to include
    value: ${{ steps.set.outputs.tag }}

runs:
  using: "composite"
  steps:
    - id: set
      shell: bash
      run: |
        set -euo pipefail

        BEFORE="${{ inputs.before }}"
        AFTER="${{ inputs.after }}"

        # Fallback when 'before' is empty (common with workflow_run)
        if [ -z "$BEFORE" ]; then
          echo "ℹ️ 'before' SHA empty; using parent of AFTER"
          BEFORE=$(git rev-parse "${AFTER}^")
        fi

        echo "Diff range: $BEFORE..$AFTER"

        CHANGED=$(git diff --name-only --diff-filter=ACMRD "$BEFORE" "$AFTER" -- || true)
        echo "Changed files:"
        echo "$CHANGED"

        TAG=""
        if echo "$CHANGED" | grep -qE '^src/'; then
          TAG="${{ inputs.service_tag }}"
          echo "✅ Emit tag: $TAG"
        else
          echo "❌ No codebase changes under 'src/' — skipping tag emission"
        fi
        
        echo "tag=$TAG" >> $GITHUB_OUTPUT