name: Deploy to Staging (Simulated)

on:
  push:
    branches: [ main ]

  workflow_dispatch:
    inputs:
      version_bump:
        description: 'Version bump type (for future use)'
        required: false
        default: none
        type: choice
        options: [major, minor, patch, none]

permissions:
  contents: read

env:
  JAVA_VERSION: 17
  APP_NAME: app-example

jobs:
  deploy:
    name: Simulate Deployment
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ env.JAVA_VERSION }}
          cache: maven

      - name: Build the App
        run: mvn clean install -DskipTests

      - name: Run Unit Tests
        run: mvn test

      - name: Simulate Docker Build
        run: |
          echo "🔧 Simulating docker build for $APP_NAME"
          echo "docker build -t fake-registry/$APP_NAME:dev ."

      - name: Simulate Docker Push
        run: |
          echo "🚀 Simulating docker push"
          echo "docker push fake-registry/$APP_NAME:dev"

      - name: Simulate Deployment Step
        run: |
          echo "📦 Pretending to deploy $APP_NAME to staging server"
          echo "✅ All good. No real containers were harmed."

      - name: Deployment Summary
        run: |
          echo "### 🚀 Simulated Deployment Summary" >> $GITHUB_STEP_SUMMARY
          echo "| Step | Status |" >> $GITHUB_STEP_SUMMARY
          echo "|------|--------|" >> $GITHUB_STEP_SUMMARY
          echo "| Build | ✅ Success |" >> $GITHUB_STEP_SUMMARY
          echo "| Unit Tests | ✅ Passed |" >> $GITHUB_STEP_SUMMARY
          echo "| Docker Build | 🔧 Simulated |" >> $GITHUB_STEP_SUMMARY
          echo "| Docker Push | 🔧 Simulated |" >> $GITHUB_STEP_SUMMARY
          echo "| Deployment | ✅ Simulated OK |" >> $GITHUB_STEP_SUMMARY
