name: Trigger UI Tests

on:
  workflow_run:
    workflows: ["Deploy to Staging (Simulated)"]
    types: [completed]

permissions:
  contents: write

jobs:
  detect-tags:
    if: ${{ github.event.workflow_run.head_branch == 'main' }}
    runs-on: ubuntu-latest
    outputs:
      tags:    ${{ steps.detect.outputs.tags }}
      matched: ${{ steps.detect.outputs.matched }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}
          fetch-depth: 2

      - name: Set tags for detected changes
        id: detect
        uses: ./.github/actions/detect-tags  # LOCAL ACTION REFERENCE
        with:
          before: ${{ github.event.workflow_run.head_commit.before }}
          after: ${{ github.event.workflow_run.head_sha }}
          filters: .github/filters/service-tags.yml

  trigger-ui-tests:
    if: ${{ needs.detect-tags.outputs.matched == 'false' }}
    needs: detect-tags
    uses: CyborgCodeSyndicate/temp-project/.github/workflows/ui-tests.yml@test-app-job
    with:
      tagsInclude: "Smoke,${{ needs.detect-tags.outputs.tags }}"
      tagsExclude: "Flaky"
      maxTestsPerJob: "20"
      maxThreadsPerJob: "10"
      maxThreadsPerSeleniumContainer: "5"
      sizePerSeleniumContainer: "2g"
      testRepoRef: "test-app-job"
    secrets: inherit