name: Trigger UI Tests from temp-project

on:
  workflow_run:
    workflows: ["Deploy to Staging (Simulated)"]
    types: [completed]

permissions:
  contents: write

jobs:
  detect-tags:
    runs-on: ubuntu-latest
    outputs:
      tags: ${{ steps.detect.outputs.tags }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_commit.id }}
          fetch-depth: 2

      - name: Debug Git history
        run: git log --oneline --graph -n 5

      - name: Detect tags to run
        id: detect
        uses: ./.github/actions/detect-tags  # LOCAL ACTION REFERENCE
        with:
          before: ${{ github.event.workflow_run.head_commit.before }}
          after: ${{ github.event.workflow_run.head_commit.id }}
          service_tag_map: |
            src/main/java/account/ -> account-service
            src/main/java/payment/ -> payment-service
  trigger-ui-tests:
    needs: detect-tags
    uses: CyborgCodeSyndicate/temp-project/.github/workflows/ui-tests.yml@test-app-job
    with:
      tagsInclude: ${{ needs.detect-tags.outputs.tags }}
      tagsExclude: "Flaky"
      maxTestsPerJob: "20"
      maxThreadsPerJob: "10"
      maxThreadsPerSeleniumContainer: "5"
      sizePerSeleniumContainer: "2g"
      testRepoRef: "test-app-job"
    secrets: inherit
