name: Trigger UI Tests from Test Repo

on:
  workflow_run:
    workflows: ["Deploy to Staging (Simulated)"]
    types:
      - completed

permissions:
  contents: write

jobs:
  trigger-ui-tests:
    name: Run UI Tests from temp-project
    uses: CyborgCodeSyndicate/temp-project/.github/workflows/ui-tests.yml@test-app-run-job
    with:
      tagsInclude: "Regression"
      tagsExclude: "Flaky"
      maxTestsPerJob: "20"
      maxThreadsPerJob: "10"
      maxThreadsPerSeleniumContainer: "5"
      sizePerSeleniumContainer: "2g"
      testRepoRef: "test-app-run-job"
    secrets: inherit