name: Trigger UI Tests

on:
  workflow_run:
    workflows: ["Deploy to Staging (Simulated)"]
    types: [completed]

permissions:
  contents: write

jobs:
  detect-tag:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.detect.outputs.tag }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_commit.id }}
          fetch-depth: 2

      - name: Set tag for detected changes
        id: detect
        uses: ./.github/actions/detect-tag  # LOCAL ACTION REFERENCE
        with:
          before: ${{ github.event.workflow_run.head_commit.before }}
          after: ${{ github.event.workflow_run.head_commit.id }}
          service_tag: account-service

  trigger-ui-tests:
    if: ${{ needs.detect-tag.outputs.tag != '' }}
    needs: detect-tag
    uses: CyborgCodeSyndicate/temp-project/.github/workflows/ui-tests.yml@test-app-job
    with:
      tagsInclude: "Smoke, ${{ needs.detect-tag.outputs.tag }}"
      tagsExclude: "Flaky"
      maxTestsPerJob: "20"
      maxThreadsPerJob: "10"
      maxThreadsPerSeleniumContainer: "5"
      sizePerSeleniumContainer: "2g"
      testRepoRef: "test-app-job"
    secrets: inherit